version: '3'
services:
  database:
    image: 'mongo'
    container_name: 'badges-dev-mongo-container'
    environment:
      - MONGO_INITDB_DATABASE=badges-dev-mongo-container
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - '27017-27019:27017-27019'